%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Plot ther data that have been extracted using the script "Main"
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Metadata
% Written by    : Nathanaël Esnault
% Verified by   : N/A
% Creation date : 2021-10-10
% Version       : 0.1 (finished on ...)
% Modifications :
% Known bugs    :

%% Functions associated with this code :

%% Possible Improvements


%%
%--------------------------------------------------------
figure;
plot(diff(framenum), 'o',...
    'LineWidth',2,...
    'Color',[0, 111, 139]./255,...
    'MarkerEdgeColor',[0, 7, 139]./255,...
    'MarkerFaceColor',[0, 111, 139]./255,...
    'MarkerSize',2)
grid on;
xlabel('Aquisition Epoch [N/A]');
ylabel('Frame Number Increment [N/A]');
title('Frame Dropout Check');

%%
%--------------------------------------------------------
figure;
plot(diff(timestamp), 'o',...
    'LineWidth',2,...
    'Color',[0, 111, 139]./255,...
    'MarkerEdgeColor',[0, 7, 139]./255,...
    'MarkerFaceColor',[0, 111, 139]./255,...
    'MarkerSize',2)
grid on;
xlabel('Aquisition Epoch [N/A]');
ylabel('Timestamp [ms]');
title('Timestamp Check');

%%
%--------------------------------------------------------
figure;
plot(fps, 'o',...
    'LineWidth',2,...
    'Color',[0, 111, 139]./255,...
    'MarkerEdgeColor',[0, 7, 139]./255,...
    'MarkerFaceColor',[0, 111, 139]./255,...
    'MarkerSize',2)
grid on;
xlabel('Aquisition Epoch [N/A]');
ylabel('FPS [N/A]');
title('Frames per seconds');

%% ======================== Attitudes ======================================
%--------------------------------------------------------
figure;
plot(t_plot, roll, '-o',...
    'LineWidth',2,...
    'Color',[219, 11, 11]./255,...
    'MarkerEdgeColor',[139, 0, 0]./255,...
    'MarkerFaceColor',[219, 11, 11]./255,...
    'MarkerSize',2,...
    'DurationTickFormat','mm:ss');
grid on;
legend(...
    'Roll',...
    'Location', 'best');
xlabel('Time [mm:ss]');
ylabel('Roll [°]');
title('Roll over time');

if Do.saveFigures
    print(gcf,'-dpng', [cd '\' SaveFiguresPath '\' RunID '\Roll over time'],['-r' num2str(saveFigureDPI)]);
end

%--------------------------------------------------------
figure;
plot(t_plot, pitch, '-o',...
    'LineWidth',2,...
    'Color',[60, 219, 11]./255,...
    'MarkerEdgeColor',[40, 133, 12]./255,...
    'MarkerFaceColor',[60, 219, 11]./255,...
    'MarkerSize',2,...
    'DurationTickFormat','mm:ss');
grid on;
legend(...
    'Pitch',...
    'Location', 'best');
xlabel('Time [mm:ss]');
ylabel('Pitch [°]');
title('Pitch over time');

%--------------------------------------------------------
figure;
plot(t_plot, yaw, '-o',...
    'LineWidth',2,...
    'Color',[255, 173, 10]./255,...
    'MarkerEdgeColor',[199, 139, 18]./255,...
    'MarkerFaceColor',[255, 173, 10]./255,...
    'MarkerSize',2,...
    'DurationTickFormat','mm:ss');
grid on;
legend(...
    'Yaw',...
    'Location', 'best');
xlabel('Time [mm:ss]');
ylabel('Yaw [°]');
title('Yaw over time');

%% 
%======================== Positions ======================================
%--------------------------------------------------------
figure;
plot(t_plot, x, '-o',...
    'LineWidth',2,...
    'Color',[219, 11, 11]./255,...
    'MarkerEdgeColor',[139, 0, 0]./255,...
    'MarkerFaceColor',[219, 11, 11]./255,...
    'MarkerSize',2,...
    'DurationTickFormat','mm:ss');
grid on;
legend(...
    'X',...
    'Location', 'best');
xlabel('Time [mm:ss]');
ylabel('X [m]');
title('X over time');

%--------------------------------------------------------
figure;
plot(t_plot, y, '-o',...
    'LineWidth',2,...
    'Color',[60, 219, 11]./255,...
    'MarkerEdgeColor',[40, 133, 12]./255,...
    'MarkerFaceColor',[60, 219, 11]./255,...
    'MarkerSize',2,...
    'DurationTickFormat','mm:ss');
grid on;
legend(...
    'Y',...
    'Location', 'best');
xlabel('Time [mm:ss]');
ylabel('Y [m]');
title('Y over time');

%--------------------------------------------------------
figure;
plot(t_plot, z, '-o',...
    'LineWidth',2,...
    'Color',[255, 173, 10]./255,...
    'MarkerEdgeColor',[199, 139, 18]./255,...
    'MarkerFaceColor',[255, 173, 10]./255,...
    'MarkerSize',2,...
    'DurationTickFormat','mm:ss');
grid on;
legend(...
    'Z',...
    'Location', 'best');
xlabel('Time [mm:ss]');
ylabel('Z [m]');
title('Z over time');



% END of file